name: Jekyll CI

on:
  push

jobs:
  build:
    inputs:
      source:
        description: 'Directory where the source files reside.'
        required: false
        default: ./
      destination:
        description: 'Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.'
        required: false
        default: ./public
      future:
        description: 'Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.'
        required: false
        default: false
      build_revision:
        description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
        required: false
        default: ${{ github.sha }}
      verbose:
        description: 'Verbose output'
        required: false
        default: true
      token:
        description: 'GitHub token'
        required: true
        default: ${{ secrets.JEKYLL_PAT }}
    runs:
      using: 'docker'
      image: 'docker://ghcr.io/actions/jekyll-build-pages:v1.0.2'

